### ISSUE TITLE
Deprecated selector in `live-archive/styles/live-archive.less`

### ISSUE THREAD

**Issue by matteocng** [mark-hahn/live-archive#19]
In `live-archive/styles/live-archive.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .la-insert .region` => `atom-text-editor.editor .la-insert .region`

* `atom-text-editor::shadow .la-replace .region` => `atom-text-editor.editor .la-replace .region`

* `atom-text-editor::shadow .la-delete .region` => `atom-text-editor.editor .la-delete .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by a7madgamal** [comment]
:(

**Comment by a7madgamal** [comment]
this should fix it https://github.com/mark-hahn/live-archive/pull/21

**Comment by irvnriir** [comment]
#21,

Version downloadable trough atom still have the issue and doesn't work, downloading it from here leading to:

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package 0.1.16


### Stack Trace

Failed to activate the live-archive package

```
At Cannot find module 'mkdirp'

Error: Cannot find module 'mkdirp'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.7/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/live-archive/lib/live-archive.coffee:17:21)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.7/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.7/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.7/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.7/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.7/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-commander 0.10.2 
atom-touch-events 0.23.0 
atom-wrap-in-tag 0.6.0 
column-select 0.2.0 
comment-anchors 0.6.1 
comment-timestamp 0.3.0 
custom-code-folder 2.4.0 
custom-folds 1.9.4 
file-watcher 1.2.6 
fold-comments 0.6.0 
fold-functions 0.5.0 
highlight-selected 0.13.1 
html-nested-comments 3.3.1 
Hydrogen 1.20.0 
intentions 1.1.5 
ioton 0.8.0 
language-arma-atom 2.11.0 
live-archive 0.1.16 
mark 1.3.3 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
outline-selection 0.3.2 
pigments 0.40.2 
plain-theme 0.7.0 
project-manager 3.3.5 
project-viewer 1.2.0 
quick-comment 0.1.3 
remember-folds 0.3.0 
scroll-through-time 0.2.0 
select-rectangle 1.0.2 
slickedit-select 1.6.2 
split-diff 1.5.1 
sublime-block-comment 0.5.1 
tool-bar 1.1.0 
```

**Comment by irvnriir** [comment]
@telonn ?
Is the  project dead ? , does it work for anyone ?

**Comment by mark-hahn** [comment]
I haven't used or worked on atom in a long time.  I would be happy if
someone took the project.  They can't do any worse than I am on it.
