### ISSUE TITLE
Uncaught TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by chovy** [mark-hahn/live-archive#3]
[Enter steps to reproduce below:]

1. clicked "Create" button from live preview menu

**Atom Version**: 0.165.0
**System**: Mac OS X 10.9.5
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.7

### Stack Trace

Uncaught TypeError: Cannot read property 'charAt' of undefined

```
At path.js:375

TypeError: Cannot read property 'charAt' of undefined
  at Object.exports.isAbsolute (path.js:375:16)
  at Object.exports.normalize (path.js:350:30)
  at Object.module.exports.openReviewEditor (/Users/username/.atom/packages/live-archive/lib/live-archive.coffee:88:26)
  at atom-workspace.<anonymous> (/Users/username/.atom/packages/live-archive/lib/live-archive.coffee:15:57)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -0:00.0 live-archive:open (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "adventurous-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
adventurous-syntax, v0.1.0
autoclose-html, v0.13.0
autocomplete-paths, v0.9.1
autocomplete-plus-async, v0.22.0
color, v0.5.0
editorconfig, v0.2.2
git-log, v0.2.0
git-tab-status, v1.3.0
live-archive, v0.1.7
save-session, vundefined

# Dev
No dev packages
```

/cc @atom/core

**Comment by mark-hahn** [comment]
I rewrote this section of code to follow the newer atom api.  Let me know
if this happens again.

Released in 0.1.8.

**Comment by mark-hahn** [comment]
I'm assuming this is fixed.

**Comment by bbbenji** [comment]
Did not seem to fix for me.

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [live-archive](https://github.com/mark-hahn/live-archive) package, v0.1.15


### Stack Trace

Uncaught TypeError: Cannot read property 'charAt' of undefined

```
At path.js:440

TypeError: Cannot read property 'charAt' of undefined
    at Object.posix.isAbsolute (path.js:440:14)
    at Object.posix.normalize (path.js:422:26)
    at Object.module.exports.openReviewEditor (/Users/benji/.atom/packages/live-archive/lib/live-archive.coffee:132:32)
    at space-pen-a.<anonymous> (/Users/benji/.atom/packages/live-archive/lib/status-bar-view.coffee:29:36)
    at space-pen-a.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-a.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:36.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:32.2.0 core:copy (atom-text-editor.editor.is-focused)
     -1:30 editor:newline (atom-text-editor.editor.is-focused)
     -1:29.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:27.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:27 core:paste (atom-text-editor.editor.is-focused)
  2x -1:22.1.0 core:undo (atom-text-editor.editor.is-focused)
     -1:20.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:20 core:paste (atom-text-editor.editor.is-focused)
     -1:17.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:17.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:57 core:paste (atom-text-editor.editor.is-focused)
  3x -0:43 core:backspace (atom-text-editor.editor.is-focused)
     -0:38.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:38.2.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
css-color-underline, v1.0.1
file-type-icons, v0.7.0
live-archive, v0.1.15
remote-sync, v3.1.2

# Dev
No dev packages
```
